alter table PIZZA_TOPPING add constraint FK_PIZZA_TOPPING_ON_INGREDIENT foreign key (INGREDIENT_ID) references PIZZA_INGREDIENT(ID);
create index IDX_PIZZA_TOPPING_ON_INGREDIENT on PIZZA_TOPPING (INGREDIENT_ID);
