alter table PIZZA_DELIVERY add constraint FK_PIZZA_DELIVERY_ON_COURIER foreign key (COURIER_ID) references SEC_USER(ID);
create unique index IDX_PIZZA_DELIVERY_UK_PHONE_NUMBER on PIZZA_DELIVERY (PHONE_NUMBER) where DELETE_TS is null ;
create index IDX_PIZZA_DELIVERY_ON_COURIER on PIZZA_DELIVERY (COURIER_ID);
