-- begin PIZZA_PAYMENT
alter table PIZZA_PAYMENT add constraint FK_PIZZA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
alter table PIZZA_PAYMENT add constraint FK_PIZZA_PAYMENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
create index IDX_PIZZA_PAYMENT_ON_ORDER on PIZZA_PAYMENT (ORDER_ID)^
create index IDX_PIZZA_PAYMENT_ON_PIZZA on PIZZA_PAYMENT (PIZZA_ID)^
-- end PIZZA_PAYMENT
-- begin PIZZA_INGREDIENT
alter table PIZZA_INGREDIENT add constraint FK_PIZZA_INGREDIENT_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
alter table PIZZA_INGREDIENT add constraint FK_PIZZA_INGREDIENT_ON_TOPING foreign key (TOPING_ID) references PIZZA_TOPPING(ID)^
create index IDX_PIZZA_INGREDIENT_ON_PIZZA on PIZZA_INGREDIENT (PIZZA_ID)^
create index IDX_PIZZA_INGREDIENT_ON_TOPING on PIZZA_INGREDIENT (TOPING_ID)^
-- end PIZZA_INGREDIENT
-- begin PIZZA_DELIVERY
alter table PIZZA_DELIVERY add constraint FK_PIZZA_DELIVERY_ON_COURIER foreign key (COURIER_ID) references SEC_USER(ID)^
create unique index IDX_PIZZA_DELIVERY_UK_PHONE_NUMBER on PIZZA_DELIVERY (PHONE_NUMBER) where DELETE_TS is null ^
create index IDX_PIZZA_DELIVERY_ON_COURIER on PIZZA_DELIVERY (COURIER_ID)^
-- end PIZZA_DELIVERY
-- begin PIZZA_TOPPING
alter table PIZZA_TOPPING add constraint FK_PIZZA_TOPPING_ON_INGREDIENT foreign key (INGREDIENT_ID) references PIZZA_INGREDIENT(ID)^
create index IDX_PIZZA_TOPPING_ON_INGREDIENT on PIZZA_TOPPING (INGREDIENT_ID)^
-- end PIZZA_TOPPING
-- begin PIZZA_ORDER
alter table PIZZA_ORDER add constraint FK_PIZZA_ORDER_ON_DELIVER foreign key (DELIVER_ID) references PIZZA_DELIVERY(ID)^
create unique index IDX_PIZZA_ORDER_UK_NUMBER_ on PIZZA_ORDER (NUMBER_) where DELETE_TS is null ^
create index IDX_PIZZA_ORDER_ON_DELIVER on PIZZA_ORDER (DELIVER_ID)^
-- end PIZZA_ORDER
